### ISSUE TITLE
Installation Script

### ISSUE THREAD

**Issue by abdullahazmy** [ToYoNiX/debian-project#1]
Start the new installation script, which contains all needed packages, offers the user to choose the DE/WM to use
Apps that they prefer

### Stage 1
- [x] Detect DE/WM a user have
- [x] Offers them to remove old ones or not
- [x] Offers them to install new DE/WM

---

### Stage 2
- [x] Detect GPU/ CPU
- [x] Detect needed drivers if we can
- [x] Install needed drivers

---

### Stage 3 (Apps)
- [x] Discord
- [x] Xournal++
- [x] Flameshot
- [x] Github Desktop

**Comment by abdullahazmy** [comment]
Now we need to work on Stage one
if we can't detect DE/WM no worries, just offer the user to download new DE/WM and use our dotfiles on them.
