### ISSUE TITLE
Linux Documentation

### ISSUE THREAD

**Issue by abdullahazmy** [ToYoNiX/debian-project#3]
Edit the README.md file

### Part 1
- [x] What is the package manager
- [x] What differs a package manager from another
- [x] Some details about APT package manager
- [ ] Some tips and tricks while using apt
- [ ] APT vs NALA

---

### Part 2
- [ ] What is shell Scripting
- [ ] How to start your first script
- [ ] Variables
- [ ] Conditions
- [ ] Loops
- [ ] Functions
